### ISSUE TITLE
NTriples output lines truncated

### ISSUE THREAD

**Issue by cwilper** [acopom/split4blank#5]
When running the utility on a current download of the NCI Thesaurus (the owl file, converted to nt), the conversion appears to succeed, however, many of the lines in the final ntriples output are invalid nt: They contain literals or bnode ids that have been truncated, such as:

```
_:B1d4e91b2X2D783cX2D44acX2Dba59X2Dfbe3551d6aff <http://www.w3.org/2002/07/owl#annotatedTarget> "HMGA2-RAD51L
```

...while the original nt file had:

```
_:B1d4e91b2X2D783cX2D44acX2Dba59X2Dfbe3551d6aff <http://www.w3.org/2002/07/owl#annotatedTarget> "HMGA2-RAD51L1 Fusion Gene" .
```

**Comment by acopom** [comment]
Thank you for reporting this bug. I have fixed it.
